readme: Add shell instructions to readme

diff --git a/README.in b/README.in
--- a/README.in
+++ b/README.in
@@ -34,6 +34,38 @@ RUN curl -fsSLo tmpl ${TMPL_URL} \
 		&& chmod +x tmpl && mv tmpl /usr/local/bin/tmpl
 ```
 
+## Safe Shell Scripting Inclusion
+
+To safely include in your shell scripts:
+```bash
+#!/bin/bash
+set -euo pipefail
+
+# Helper Functions
+case "${OSTYPE}" in
+linux*) platform=linux
+	;;
+darwin*)
+	platform=darwin
+	;;
+*) platform=unknown ;;
+esac
+
+function install_tmpl() {
+  if [[ "${platform}" == "darwin" ]]; then
+    TMPL_SHA256SUM={{ .MACOS_SHASUM }}
+  else
+    TMPL_SHA256SUM={{ .LINUX_SHASUM }}
+  fi
+  TMPL_URL=https://github.com/tmc/tmpl/releases/download/{{ .LATEST_TAG }}/tmpl_${platform}_amd64
+  curl -fsSLo tmpl ${TMPL_URL} \
+    && echo "${TMPL_SHA256SUM}  tmpl" | sha256sum -c - \
+    && chmod +x tmpl
+  mv tmpl /usr/local/bin/tmpl || echo "could not move tmpl into place"
+}
+
+command -v tmpl > /dev/null || install_tmpl
+```
 
 ### Example 1
 Given a file 'a' with contents:
